import CheckoutContent from '@/components/checkout';
import OrderSummary from '@/components/checkout/OrderSummary';
import React from 'react';

export const metadata = {
    title: 'Checkout || Korean Mall',
    description: 'Generated by Korean Mall Checkout Page',
}

const CheckoutPage = () => {
    return (
        <div className='container mx-auto my-5 md:my-10'>
            <div className='mx-4 md:mx-0'>
                <div className='border-dotted border-b pb-5 border-b-dark'>
                    <h1 className='text-gray-800 text-2xl text-center font-medium'>Checkout</h1>
                </div>

                <div className='flex gap-4 mt-4'>
                    <div className='md:w-3/5'>
                        <CheckoutContent />
                    </div>
                    <div className='md:w-2/5'>
                        <OrderSummary />
                    </div>
                </div>
            </div>
        </div>
    );
};

export default CheckoutPage;