import ProductDescription from '@/components/productDetails/ProductDescription';
import Image from 'next/image';
import React from 'react';
import MightAlsoSection from '@/components/productDetails/MightAlsoSection';
import MoreProducts from '@/components/productDetails/MoreProducts';
import ReviewSection from '@/components/productDetails/reviewSection';
import { getSingleProduct } from '@/config/productsApi';

export const metadata = {
    title: 'Biome Radiating Intensified Essence || Korean Mall',
    description: 'Generated by Korean Mall Product Details',
}

const ProductDetailsPage = async ({ params }) => {
    const { slug } = params || {};
    const { data: product } = await getSingleProduct(slug) || {};
    const { name, images, _id, manufacturer } = product?.result || {};

    return (
        <div className='container mx-auto my-10 md:my-20'>
            <div className='mx-4 md:mx-0'>
                <div className='md:flex items-start gap-20'>
                    <div className='w-full md:w-1/2 flex gap-2 mb-4 lg:mb-0 sticky top-10'>
                        <div className='w-1/4 overflow-y-scroll h-[16rem] lg:h-[28rem] details-image'>
                            {
                                images?.map((img) =>
                                    <Image
                                        key={img}
                                        className='h-auto w-full border mb-2'
                                        height={720}
                                        width={1280}
                                        src={img}
                                        alt={name} />
                                )
                            }
                        </div>
                        <div className='w-full'>
                            <Image className='h-auto w-full' height={720} width={1280} src={images[0]} alt={name} />
                        </div>
                    </div>
                    <div className='w-full md:w-1/2'>
                        <ProductDescription product={product?.result} />
                    </div>
                </div>
            </div>
            <MightAlsoSection id={slug} />
            <MoreProducts brandId={manufacturer?._id} />
            <ReviewSection />
        </div>
    );
};

export default ProductDetailsPage;