import { Inter } from 'next/font/google'
import './globals.css'
import TopNav from '@/shared/topNav/TopNav'
import Header from '@/shared/header/Header'
import Navbar from '@/shared/navbar/Navbar'
import Footer from '@/shared/footer/Footer'
import ThemeConfig from "@/utilities/themeConfig/ThemeConfig";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Korean Mall',
  description: 'Generated by Korean Mall',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeConfig />
        <TopNav />
        <Header />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
