import { Inter } from 'next/font/google'
import './globals.css'
import TopNav from '@/shared/topNav/TopNav'
import Header from '@/shared/header/Header'
import Navbar from '@/shared/navbar/Navbar'
import Footer from '@/shared/footer/Footer'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import ThemeConfig from "@/utilities/themeConfig/ThemeConfig";
import BackToTop from '@/utilities/backToTop/BackToTop'
import AuthProvider from '@/context/AuthProvider'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Korean Mall',
  description: 'Generated by Korean Mall',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeConfig />
          <BackToTop />
          <TopNav />
          <Header />
          <Navbar />
          {children}
          <Footer />
        </AuthProvider>
        <Toaster/>
      </body>
    </html>
  )
}
