import SearchSidebar from '@/components/productsSearch/sidebar/SearchSidebar';
import SearchTopbar from '@/components/productsSearch/topbar/SearchTopbar';
import React from 'react';

export const metadata = {
    title: 'Korean Mall',
    description: 'Generated by Korean Mall',
}

const layout = ({ children }) => {
    return (
        <div className='container mx-auto my-10'>
            <div className='mx-4 md:mx-0 flex'>
                <div className='w-1/4'>
                    <SearchSidebar />
                </div>
                <div className='w-3/4'>
                    <div>
                        <SearchTopbar />
                    </div>
                    <div>
                        {children}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default layout;